### ISSUE TITLE
Mistake in My First LLVM Compiler post

### ISSUE THREAD

**Issue by s4chin** [Wilfred/wilfred.github.com#3]
The code in the Hand-compiling + section reads
```
%cell_index = load i8* %cell_index_ptr 
%cell_ptr = getelementptr i8* %cells, i8 %cell_index
```
Instead it should read
```
%cell_index = load i32* %cell_index_ptr 
%cell_ptr = getelementptr i8* %cells, i32 %cell_index
```
The mistake is only in the post and not in the [skeleton](https://github.com/Wilfred/Brainfrack/blob/a86c4ee50e35d38e3cb3cb826c1d68de8898ef06/llvm/increment.ll).

**Comment by Wilfred** [comment]
Well spotted! Thanks :)
